const COMMANDS = [
// ===== File & Directory =====
{cat:"file",cmd:"ls",desc:"List directory contents",ex:"ls -lah /home\nls -lt *.txt",tags:"list,dir"},
{cat:"file",cmd:"cd",desc:"Change directory",ex:"cd /var/log\ncd ..\ncd ~",tags:"navigate"},
{cat:"file",cmd:"pwd",desc:"Print working directory",ex:"pwd",tags:"path"},
{cat:"file",cmd:"mkdir",desc:"Create directories",ex:"mkdir -p projects/src/main\nmkdir new_folder",tags:"create,dir"},
{cat:"file",cmd:"rmdir",desc:"Remove empty directories",ex:"rmdir empty_folder",tags:"remove,dir"},
{cat:"file",cmd:"rm",desc:"Remove files or directories",ex:"rm -rf old_project\nrm *.tmp\nrm -i important.txt",tags:"delete,remove"},
{cat:"file",cmd:"cp",desc:"Copy files and directories",ex:"cp -r src/ dest/\ncp file.txt backup.txt\ncp -i *.txt /backup/",tags:"copy"},
{cat:"file",cmd:"mv",desc:"Move or rename files",ex:"mv old.txt new.txt\nmv file.txt /tmp/\nmv -v *.log logs/",tags:"move,rename"},
{cat:"file",cmd:"touch",desc:"Create empty files or update timestamps",ex:"touch newfile.txt\ntouch -t 202601010000 file.txt",tags:"create"},
{cat:"file",cmd:"find",desc:"Search for files in a directory hierarchy",ex:"find / -name '*.conf'\nfind . -type f -size +100M\nfind /var -mtime -1",tags:"search"},
{cat:"file",cmd:"locate",desc:"Find files by name (uses database)",ex:"locate nginx.conf\nlocate -i readme",tags:"search,fast"},
{cat:"file",cmd:"tree",desc:"Display directory tree structure",ex:"tree -L 2\ntree -a --dirsfirst",tags:"visualize"},
{cat:"file",cmd:"stat",desc:"Display file or file system status",ex:"stat file.txt\nstat -f /  # filesystem info",tags:"info,metadata"},
{cat:"file",cmd:"file",desc:"Determine file type",ex:"file document.pdf\nfile *.png",tags:"type,info"},
{cat:"file",cmd:"ln",desc:"Create hard and symbolic links",ex:"ln -s /var/www html\nln target.txt hardlink.txt",tags:"symlink,link"},
{cat:"file",cmd:"rename",desc:"Rename multiple files",ex:"rename 's/\\.old/.new/' *.old\nrename 'y/A-Z/a-z/' *.TXT",tags:"batch,rename"},
{cat:"file",cmd:"du",desc:"Estimate file and directory space usage",ex:"du -sh /home\ndu -h --max-depth=1\ndu -a | sort -n",tags:"size,disk"},
{cat:"file",cmd:"df",desc:"Report file system disk space usage",ex:"df -h\ndf -h --type=ext4\ndf -i",tags:"disk,space"},

// ===== File Content / Text =====
{cat:"text",cmd:"cat",desc:"Concatenate and display file content",ex:"cat file.txt\ncat -n file.txt  # with line numbers\ncat > newfile.txt  # write",tags:"view,concat"},
{cat:"text",cmd:"less",desc:"View file content page by page",ex:"less largefile.log\nless +F /var/log/syslog  # tail mode",tags:"view,pager"},
{cat:"text",cmd:"more",desc:"View file content page by page",ex:"more file.txt",tags:"view,pager"},
{cat:"text",cmd:"head",desc:"Output the first part of files",ex:"head -n 20 file.txt\nhead -c 1000 binary.dat",tags:"view,top"},
{cat:"text",cmd:"tail",desc:"Output the last part of files",ex:"tail -n 50 log.txt\ntail -f /var/log/syslog  # follow\ntail -f --pid=$$ file",tags:"view,bottom,follow"},
{cat:"text",cmd:"grep",desc:"Search text using patterns",ex:"grep -rn 'error' /var/log\ngrep -i 'warning' file.txt\ngrep -v '#' config.conf\ngrep -E 'foo|bar' file",tags:"search,filter"},
{cat:"text",cmd:"egrep",desc:"Extended grep (grep -E)",ex:"egrep 'foo|bar' file.txt",tags:"search,regex"},
{cat:"text",cmd:"sed",desc:"Stream editor for text transformation",ex:"sed 's/old/new/g' file.txt\nsed -i 's/foo/bar/g' *.conf\nsed -n '5,10p' file.txt",tags:"edit,replace"},
{cat:"text",cmd:"awk",desc:"Pattern scanning and text processing",ex:"awk '{print $2}' file.txt\nawk -F: '{print $1}' /etc/passwd\nawk 'NR>1 && $3>100' data.csv",tags:"process,column"},
{cat:"text",cmd:"sort",desc:"Sort lines of text files",ex:"sort file.txt\nsort -r -n numbers.txt\nsort -u -t: -k3 /etc/passwd",tags:"sort"},
{cat:"text",cmd:"uniq",desc:"Report or omit repeated lines",ex:"sort file | uniq\nsort file | uniq -c | sort -rn",tags:"deduplicate"},
{cat:"text",cmd:"cut",desc:"Remove sections from each line",ex:"cut -d: -f1 /etc/passwd\ncut -c1-10 file.txt\ncut -f2 -d',' data.csv",tags:"extract,column"},
{cat:"text",cmd:"paste",desc:"Merge lines of files",ex:"paste file1.txt file2.txt\npaste -d',' col1.txt col2.txt",tags:"merge"},
{cat:"text",cmd:"tr",desc:"Translate or delete characters",ex:"echo 'Hello' | tr 'a-z' 'A-Z'\ntr -d '\\n' < file.txt\ntr -s ' ' < file.txt",tags:"translate,replace"},
{cat:"text",cmd:"wc",desc:"Count words, lines, and bytes",ex:"wc -l file.txt\nwc -w *.txt\nwc -c file.dat",tags:"count"},
{cat:"text",cmd:"diff",desc:"Compare files line by line",ex:"diff file1.txt file2.txt\ndiff -u old.conf new.conf\ndiff -r dir1/ dir2/",tags:"compare"},
{cat:"text",cmd:"tee",desc:"Read from stdin and write to stdout and files",ex:"echo 'log' | tee file.txt\ncmd | tee -a logfile.txt",tags:"redirect,duplicate"},
{cat:"text",cmd:"xargs",desc:"Build and execute command lines from stdin",ex:"find . -name '*.tmp' | xargs rm\nfind . -type f | xargs grep 'pattern'\necho '1 2 3' | xargs -n1 echo",tags:"pipeline"},
{cat:"text",cmd:"nl",desc:"Number lines of files",ex:"nl file.txt\nnl -ba file.txt",tags:"number,lines"},
{cat:"text",cmd:"tac",desc:"Concatenate and print files in reverse",ex:"tac file.txt",tags:"reverse"},
{cat:"text",cmd:"rev",desc:"Reverse lines character by character",ex:"echo 'hello' | rev  # olleh",tags:"reverse"},
{cat:"text",cmd:"fold",desc:"Wrap each input line to fit in specified width",ex:"fold -w 80 file.txt\nfold -w 40 -s file.txt",tags:"wrap"},
{cat:"text",cmd:"column",desc:"Columnate lists",ex:"column -t -s',' data.csv\ncat /etc/passwd | column -t -s:",tags:"format,table"},
{cat:"text",cmd:"expand",desc:"Convert tabs to spaces",ex:"expand -t 4 file.txt",tags:"tabs"},
{cat:"text",cmd:"unexpand",desc:"Convert spaces to tabs",ex:"unexpand -t 4 file.txt",tags:"tabs"},

// ===== Permissions & Ownership =====
{cat:"perms",cmd:"chmod",desc:"Change file mode bits",ex:"chmod 755 script.sh\nchmod +x file\nchmod -R 644 /var/www\nchmod u+x,g-w file.txt",tags:"permission"},
{cat:"perms",cmd:"chown",desc:"Change file owner and group",ex:"chown user:group file.txt\nchown -R www-data:www-data /var/www",tags:"owner"},
{cat:"perms",cmd:"chgrp",desc:"Change group ownership",ex:"chgrp developers project/\nchgrp -R staff /shared",tags:"group"},
{cat:"perms",cmd:"umask",desc:"Set default file creation mask",ex:"umask 022\numask 077\numask -S",tags:"default,permission"},
{cat:"perms",cmd:"setfacl",desc:"Set file access control lists",ex:"setfacl -m u:john:rwx file.txt\nsetfacl -R -m g:dev:rw /project",tags:"acl"},
{cat:"perms",cmd:"getfacl",desc:"Get file access control lists",ex:"getfacl file.txt\ngetfacl -R /project",tags:"acl"},
{cat:"perms",cmd:"sudo",desc:"Execute a command as superuser",ex:"sudo apt update\nsudo -u www-data ls /var/www\nsudo -i  # root shell",tags:"root,admin"},
{cat:"perms",cmd:"su",desc:"Switch user",ex:"su - username\nsu -  # switch to root",tags:"switch,user"},

// ===== Process Management =====
{cat:"process",cmd:"ps",desc:"Report a snapshot of current processes",ex:"ps aux\nps -ef | grep nginx\nps -eo pid,user,%mem,cmd --sort=-%mem",tags:"list,process"},
{cat:"process",cmd:"top",desc:"Display Linux processes (interactive)",ex:"top\ntop -c -b -n1\ntop -u username",tags:"monitor,realtime"},
{cat:"process",cmd:"htop",desc:"Interactive process viewer (enhanced top)",ex:"htop\nhtop -u root\nhtop -p 1234",tags:"monitor"},
{cat:"process",cmd:"kill",desc:"Send a signal to a process",ex:"kill 1234\nkill -9 1234  # SIGKILL\nkill -TERM $(pgrep nginx)",tags:"terminate,signal"},
{cat:"process",cmd:"killall",desc:"Kill processes by name",ex:"killall firefox\nkillall -9 nginx\nkillall -u username",tags:"terminate,name"},
{cat:"process",cmd:"pkill",desc:"Signal processes by pattern",ex:"pkill -f 'python script.py'\npkill -u guest\npkill -9 sshd",tags:"kill,pattern"},
{cat:"process",cmd:"pgrep",desc:"Look up processes by name",ex:"pgrep nginx\npgrep -u root sshd\npgrep -l python",tags:"find,process"},
{cat:"process",cmd:"jobs",desc:"List active jobs",ex:"jobs\njobs -l",tags:"background"},
{cat:"process",cmd:"bg",desc:"Resume jobs in background",ex:"bg %1\nCtrl+Z then bg",tags:"background"},
{cat:"process",cmd:"fg",desc:"Bring jobs to foreground",ex:"fg %1",tags:"foreground"},
{cat:"process",cmd:"nohup",desc:"Run command immune to hangups",ex:"nohup python script.py &\nnohup ./server > log.txt 2>&1 &",tags:"background,persist"},
{cat:"process",cmd:"screen",desc:"Terminal multiplexer (sessions)",ex:"screen -S mysession\nscreen -ls\nscreen -r mysession",tags:"session,multiplex"},
{cat:"process",cmd:"tmux",desc:"Terminal multiplexer (modern)",ex:"tmux new -s work\ntmux ls\ntmux attach -t work\nCtrl+B then D  # detach",tags:"session,multiplex"},
{cat:"process",cmd:"nice",desc:"Run with modified scheduling priority",ex:"nice -n 10 ./backup.sh\nnice -n -5 high_priority_task",tags:"priority"},
{cat:"process",cmd:"renice",desc:"Alter priority of running process",ex:"renice -n 5 -p 1234\nrenice +10 -u username",tags:"priority"},
{cat:"process",cmd:"time",desc:"Measure command execution time",ex:"time ./script.sh\ntime wget url",tags:"benchmark"},
{cat:"process",cmd:"watch",desc:"Execute a command periodically",ex:"watch -n 2 'ls -la'\nwatch -n 5 df -h\nwatch -d free -m",tags:"monitor,repeat"},

// ===== Networking =====
{cat:"net",cmd:"ping",desc:"Send ICMP echo requests",ex:"ping google.com\nping -c 4 8.8.8.8\nping -i 2 host.com",tags:"connectivity,test"},
{cat:"net",cmd:"curl",desc:"Transfer data from URLs",ex:"curl https://example.com\ncurl -O https://site.com/file.zip\ncurl -X POST -d 'data' https://api.com\ncurl -H 'Content-Type: application/json' -d '{\"k\":\"v\"}' url",tags:"http,download,api"},
{cat:"net",cmd:"wget",desc:"Non-interactive network downloader",ex:"wget https://site.com/file.zip\nwget -c url  # resume\nwget -r -l2 https://site.com  # recursive\nwget -m https://site.com  # mirror",tags:"download"},
{cat:"net",cmd:"ssh",desc:"Secure shell remote login",ex:"ssh user@host.com\nssh -p 2222 user@host\nssh -i key.pem user@host\nssh -L 8080:localhost:80 user@host  # tunnel",tags:"remote,secure"},
{cat:"net",cmd:"scp",desc:"Secure copy over SSH",ex:"scp file.txt user@host:/path/\nscp -r dir/ user@host:/dest/\nscp -P 2222 file user@host:.",tags:"copy,remote"},
{cat:"net",cmd:"rsync",desc:"Efficient file synchronization",ex:"rsync -avz src/ user@host:/dest/\nrsync -avz --delete src/ dest/\nrsync -avz -e 'ssh -p 2222' src/ host:/dest/",tags:"sync,backup"},
{cat:"net",cmd:"netstat",desc:"Network connections and statistics",ex:"netstat -tlnp\nnetstat -an | grep :80\nnetstat -rn  # routing table",tags:"connections,ports"},
{cat:"net",cmd:"ss",desc:"Socket statistics (modern netstat)",ex:"ss -tlnp\nss -tulpn\nss -s  # summary",tags:"sockets,ports"},
{cat:"net",cmd:"ifconfig",desc:"Configure network interfaces",ex:"ifconfig\nifconfig eth0 up\nifconfig eth0 192.168.1.10 netmask 255.255.255.0",tags:"interface"},
{cat:"net",cmd:"ip",desc:"Show/manipulate routing, devices (modern)",ex:"ip addr show\nip route\nip link set eth0 up\nip -s link",tags:"interface,routing"},
{cat:"net",cmd:"traceroute",desc:"Trace network path to host",ex:"traceroute google.com\ntraceroute -n 8.8.8.8",tags:"trace,routing"},
{cat:"net",cmd:"nslookup",desc:"Query DNS records",ex:"nslookup example.com\nnslookup -type=MX domain.com",tags:"dns"},
{cat:"net",cmd:"dig",desc:"DNS lookup utility (advanced)",ex:"dig example.com\ndig +short MX domain.com\ndig @8.8.8.8 example.com",tags:"dns"},
{cat:"net",cmd:"host",desc:"DNS lookup simple",ex:"host google.com\nhost -t MX gmail.com",tags:"dns"},
{cat:"net",cmd:"nmap",desc:"Network scanner / port scanner",ex:"nmap 192.168.1.0/24\nnmap -sS -O target.com\nnmap -p 80,443 host.com",tags:"scan,security"},
{cat:"net",cmd:"tcpdump",desc:"Dump network traffic",ex:"tcpdump -i eth0\ntcpdump -i eth0 port 80\ntcpdump -nn -w capture.pcap",tags:"capture,sniff"},
{cat:"net",cmd:"nc",desc:"Netcat - network utility",ex:"nc -l 8080  # listen\nnc host.com 80  # connect\necho 'test' | nc host 8080",tags:"netcat,debug"},
{cat:"net",cmd:"whois",desc:"Query WHOIS domain info",ex:"whois example.com\nwhois 8.8.8.8",tags:"domain,info"},
{cat:"net",cmd:"ftp",desc:"File transfer protocol client",ex:"ftp host.com\nftp -s:script.txt host.com",tags:"transfer"},
{cat:"net",cmd:"telnet",desc:"Telnet protocol client",ex:"telnet host.com 80\ntelnet localhost 3306",tags:"connect,debug"},

// ===== Package Management =====
{cat:"pkg",cmd:"apt",desc:"Debian/Ubuntu package manager",ex:"sudo apt update && sudo apt upgrade\nsudo apt install nginx\nsudo apt remove --purge nginx\napt search keyword\napt list --installed",tags:"debian,ubuntu"},
{cat:"pkg",cmd:"apt-get",desc:"Debian package handling (lower-level)",ex:"sudo apt-get update\nsudo apt-get install -y package\nsudo apt-get autoremove",tags:"debian"},
{cat:"pkg",cmd:"dpkg",desc:"Debian package installer (low-level)",ex:"dpkg -i package.deb\ndpkg -r package\n dpkg -l | grep nginx\ndpkg -L package",tags:"debian,deb"},
{cat:"pkg",cmd:"yum",desc:"RHEL/CentOS package manager",ex:"sudo yum install nginx\nsudo yum update\nyum search keyword\nyum list installed",tags:"rhel,centos"},
{cat:"pkg",cmd:"dnf",desc:"Fedora package manager (modern yum)",ex:"sudo dnf install package\nsudo dnf upgrade\ndnf search keyword",tags:"fedora"},
{cat:"pkg",cmd:"rpm",desc:"RPM package manager",ex:"rpm -ivh package.rpm\nrpm -e package\nrpm -qa | grep nginx\nrpm -ql package",tags:"rpm"},
{cat:"pkg",cmd:"pacman",desc:"Arch Linux package manager",ex:"sudo pacman -Syu  # update\nsudo pacman -S package\npacman -Ss keyword\npacman -Ql package",tags:"arch"},
{cat:"pkg",cmd:"snap",desc:"Snap package manager",ex:"sudo snap install package\nsudo snap list\nsudo snap remove package",tags:"snap,universal"},
{cat:"pkg",cmd:"flatpak",desc:"Flatpak application manager",ex:"flatpak install flathub app.id\nflatpak list\nflatpak run app.id",tags:"flatpak"},
{cat:"pkg",cmd:"pip",desc:"Python package installer",ex:"pip install package\npip install -r requirements.txt\npip freeze > requirements.txt\npip uninstall package",tags:"python"},
{cat:"pkg",cmd:"npm",desc:"Node.js package manager",ex:"npm install package\nnpm install -g package\nnpm update\nnpm list -g --depth=0",tags:"nodejs"},
{cat:"pkg",cmd:"gem",desc:"Ruby package manager",ex:"gem install package\ngem list\ngem update",tags:"ruby"},
{cat:"pkg",cmd:"cargo",desc:"Rust package manager",ex:"cargo new project\ncargo build\ncargo add crate-name\ncargo run",tags:"rust"},

// ===== Compression & Archive =====
{cat:"archive",cmd:"tar",desc:"Archive utility (tarballs)",ex:"tar -czvf archive.tar.gz dir/\ntar -xzvf archive.tar.gz\ntar -tf archive.tar.gz  # list\ntar -cjvf archive.tar.bz2 dir/",tags:"tarball,gzip"},
{cat:"archive",cmd:"gzip",desc:"Compress files (gzip)",ex:"gzip file.txt  # creates .gz\ngzip -k file.txt  # keep original\ngzip -d file.gz  # decompress",tags:"compress,gz"},
{cat:"archive",cmd:"gunzip",desc:"Decompress gzip files",ex:"gunzip file.gz\ngunzip -c file.gz > output.txt",tags:"decompress"},
{cat:"archive",cmd:"zip",desc:"Package and compress files",ex:"zip -r archive.zip dir/\nzip -e secret.zip file.txt  # encrypt\nzip -9 max.zip *.txt  # max compression",tags:"compress"},
{cat:"archive",cmd:"unzip",desc:"Extract ZIP files",ex:"unzip archive.zip\nunzip -d /target archive.zip\nunzip -l archive.zip  # list",tags:"extract"},
{cat:"archive",cmd:"bzip2",desc:"Block-sorting file compressor",ex:"bzip2 file.txt  # creates .bz2\nbzip2 -d file.bz2  # decompress\nbzip2 -k file.txt  # keep original",tags:"compress,bz2"},
{cat:"archive",cmd:"xz",desc:"General-purpose data compression",ex:"xz file.txt\nxz -d file.xz\nxz -k -9 file.txt  # max compression",tags:"compress,xz"},
{cat:"archive",cmd:"7z",desc:"7-Zip archiver",ex:"7z a archive.7z dir/\n7z x archive.7z\n7z l archive.7z  # list",tags:"compress,7zip"},
{cat:"archive",cmd:"zcat",desc:"View compressed files",ex:"zcat file.gz\nzcat access.log.gz | grep 'error'",tags:"view,compressed"},
{cat:"archive",cmd:"zgrep",desc:"Search inside compressed files",ex:"zgrep 'error' log.gz\nzgrep -i 'warning' *.gz",tags:"search,compressed"},

// ===== System Information =====
{cat:"system",cmd:"uname",desc:"Print system information",ex:"uname -a\nuname -r  # kernel version\nuname -m  # architecture",tags:"kernel,info"},
{cat:"system",cmd:"hostname",desc:"Show or set system hostname",ex:"hostname\nhostname -I  # IP addresses\nhostnamectl set-hostname newname",tags:"hostname"},
{cat:"system",cmd:"uptime",desc:"Show system uptime and load",ex:"uptime\nuptime -p  # pretty format",tags:"uptime,load"},
{cat:"system",cmd:"free",desc:"Display memory usage",ex:"free -h\nfree -m\nfree -s 5  # update every 5s",tags:"memory,ram"},
{cat:"system",cmd:"lscpu",desc:"Display CPU information",ex:"lscpu\nlscpu | grep 'Model name'",tags:"cpu"},
{cat:"system",cmd:"lsblk",desc:"List block devices",ex:"lsblk\nlsblk -f\nlsblk -o NAME,SIZE,TYPE,MOUNTPOINT",tags:"disk,block"},
{cat:"system",cmd:"lspci",desc:"List PCI devices",ex:"lspci\nlspci -v  # verbose\nlspci | grep -i vga",tags:"hardware,pci"},
{cat:"system",cmd:"lsusb",desc:"List USB devices",ex:"lsusb\nlsusb -v",tags:"hardware,usb"},
{cat:"system",cmd:"dmidecode",desc:"DMI (SMBIOS) table decoder",ex:"sudo dmidecode -t memory\nsudo dmidecode -t system\nsudo dmidecode -t bios",tags:"hardware,info"},
{cat:"system",cmd:"hwinfo",desc:"Hardware information",ex:"hwinfo --short\nhwinfo --cpu\nhwinfo --network",tags:"hardware"},
{cat:"system",cmd:"lsof",desc:"List open files",ex:"lsof -i :80  # port 80\nlsof -u username\nlsof /var/log/syslog\nlsof -p 1234",tags:"files,open"},
{cat:"system",cmd:"dmesg",desc:"Print kernel ring buffer",ex:"dmesg\ndmesg | tail -50\ndmesg --level=err,warn",tags:"kernel,log"},
{cat:"system",cmd:"journalctl",desc:"Query systemd journal",ex:"journalctl -u nginx\njournalctl --since today\njournalctl -f  # follow\njournalctl -p err",tags:"log,systemd"},
{cat:"system",cmd:"systemctl",desc:"Control systemd services",ex:"sudo systemctl start nginx\nsudo systemctl enable nginx\nsystemctl status nginx\nsystemctl restart nginx",tags:"service,systemd"},
{cat:"system",cmd:"service",desc:"Run a system service (init.d)",ex:"sudo service nginx start\nsudo service nginx status\nservice --status-all",tags:"service"},
{cat:"system",cmd:"date",desc:"Display or set date/time",ex:"date\ndate '+%Y-%m-%d %H:%M:%S'\ndate -u  # UTC\nsudo date -s '2026-07-25 10:00:00'",tags:"time,date"},
{cat:"system",cmd:"timedatectl",desc:"Control system time and date",ex:"timedatectl\ntimedatectl set-timezone Asia/Shanghai\ntimedatectl set-ntp true",tags:"timezone"},
{cat:"system",cmd:"cal",desc:"Display a calendar",ex:"cal\ncal -3  # 3 months\ncal 2026\ncal -y",tags:"calendar"},
{cat:"system",cmd:"who",desc:"Show who is logged in",ex:"who\nwho -b  # boot time\nwho -q  # count",tags:"users,login"},
{cat:"system",cmd:"w",desc:"Show who is logged in and what they do",ex:"w\nw username",tags:"users,activity"},
{cat:"system",cmd:"last",desc:"Show last logged in users",ex:"last\nlast -10\nlast -x reboot",tags:"login,history"},
{cat:"system",cmd:"history",desc:"Show command history",ex:"history\nhistory | grep ssh\n!123  # run command 123\nclear history: history -c",tags:"history"},

// ===== Disk & Storage =====
{cat:"disk",cmd:"fdisk",desc:"Manipulate disk partition table",ex:"sudo fdisk -l\nsudo fdisk /dev/sda",tags:"partition"},
{cat:"disk",cmd:"parted",desc:"Partition editor",ex:"sudo parted -l\nsudo parted /dev/sda",tags:"partition"},
{cat:"disk",cmd:"mkfs",desc:"Create a filesystem",ex:"sudo mkfs.ext4 /dev/sda1\nsudo mkfs.ntfs -f /dev/sdb1\nsudo mkfs.xfs /dev/sdc1",tags:"format,filesystem"},
{cat:"disk",cmd:"mount",desc:"Mount a filesystem",ex:"sudo mount /dev/sda1 /mnt\nsudo mount -t nfs host:/share /mnt\nmount | column -t",tags:"mount"},
{cat:"disk",cmd:"umount",desc:"Unmount a filesystem",ex:"sudo umount /mnt\nsudo umount -l /mnt  # lazy",tags:"unmount"},
{cat:"disk",cmd:"fsck",desc:"Check and repair filesystem",ex:"sudo fsck /dev/sda1\nsudo fsck -y /dev/sda1",tags:"check,repair"},
{cat:"disk",cmd:"dd",desc:"Convert and copy files (low-level)",ex:"sudo dd if=/dev/sda of=disk.img bs=4M\nsudo dd if=iso of=/dev/sdb bs=4M status=progress",tags:"clone,image"},
{cat:"disk",cmd:"blkid",desc:"Locate/print block device attributes",ex:"blkid\nblkid /dev/sda1",tags:"uuid,block"},
{cat:"disk",cmd:"smartctl",desc:"SMART disk health monitoring",ex:"sudo smartctl -a /dev/sda\nsudo smartctl -t short /dev/sda",tags:"health,disk"},
{cat:"disk",cmd:"iostat",desc:"I/O statistics",ex:"iostat\niostat -x 2\niostat -d sda",tags:"io,stats"},
{cat:"disk",cmd:"ncdu",desc:"NCurses disk usage analyzer",ex:"ncdu /\nncdu /var\nncdu -x /  # one filesystem",tags:"disk,analyze"},

// ===== User & Group =====
{cat:"user",cmd:"useradd",desc:"Create a new user",ex:"sudo useradd -m -s /bin/bash username\nsudo useradd -m -G sudo,docker username",tags:"create,user"},
{cat:"user",cmd:"usermod",desc:"Modify a user account",ex:"sudo usermod -aG docker username\nsudo usermod -L username  # lock\nsudo usermod -s /bin/zsh username",tags:"modify,user"},
{cat:"user",cmd:"userdel",desc:"Delete a user account",ex:"sudo userdel username\nsudo userdel -r username  # remove home",tags:"delete,user"},
{cat:"user",cmd:"passwd",desc:"Change user password",ex:"passwd  # change own\nsudo passwd username\npasswd -l username  # lock",tags:"password"},
{cat:"user",cmd:"groupadd",desc:"Create a new group",ex:"sudo groupadd developers\nsudo groupadd -g 2000 team",tags:"group,create"},
{cat:"user",cmd:"groupdel",desc:"Delete a group",ex:"sudo groupdel developers",tags:"group,delete"},
{cat:"user",cmd:"gpasswd",desc:"Administer /etc/group",ex:"sudo gpasswd -a username docker\nsudo gpasswd -d username docker",tags:"group,member"},
{cat:"user",cmd:"id",desc:"Print user and group IDs",ex:"id\nid username\nid -Gn username",tags:"identity"},
{cat:"user",cmd:"groups",desc:"Show group memberships",ex:"groups\ngroups username",tags:"group"},
{cat:"user",cmd:"whoami",desc:"Print current user name",ex:"whoami",tags:"identity"},

// ===== Text Editors =====
{cat:"editor",cmd:"vim",desc:"Vi IMproved text editor",ex:"vim file.txt\nvim +42 file.txt  # jump to line\n:q!  # quit without save\n:wq  # save and quit",tags:"editor,vi"},
{cat:"editor",cmd:"nano",desc:"Simple text editor",ex:"nano file.txt\nnano -l file.txt  # line numbers\nCtrl+O to save, Ctrl+X to exit",tags:"editor,simple"},
{cat:"editor",cmd:"vi",desc:"Standard vi editor",ex:"vi file.txt\n:wq  # save & quit\n:q!  # force quit",tags:"editor"},
{cat:"editor",cmd:"emacs",desc:"GNU Emacs editor",ex:"emacs file.txt\nemacs -nw file.txt  # no window",tags:"editor"},

// ===== Shell & Scripting =====
{cat:"shell",cmd:"echo",desc:"Display a line of text",ex:"echo 'Hello World'\necho -e 'Line1\\nLine2'\necho $PATH\necho {1..10}",tags:"print"},
{cat:"shell",cmd:"printf",desc:"Format and print data",ex:"printf '%s\\n' 'Hello'\nprintf '%-10s %5d\\n' 'Name' 42",tags:"format,print"},
{cat:"shell",cmd:"export",desc:"Set environment variables",ex:"export PATH=$PATH:/new/bin\nexport MY_VAR='value'\nexport -p  # list all",tags:"env,variable"},
{cat:"shell",cmd:"alias",desc:"Create command aliases",ex:"alias ll='ls -lah'\nalias ..='cd ..'\nalias  # list all",tags:"shortcut"},
{cat:"shell",cmd:"source",desc:"Execute commands from a file",ex:"source ~/.bashrc\nsource venv/bin/activate\n. script.sh",tags:"execute,import"},
{cat:"shell",cmd:"env",desc:"Run command in modified environment",ex:"env\nenv VAR=value command\nenv -i command  # clean env",tags:"environment"},
{cat:"shell",cmd:"set",desc:"Set shell options and positional params",ex:"set -e  # exit on error\nset -x  # debug\nset -o pipefail",tags:"shell,options"},
{cat:"shell",cmd:"unset",desc:"Remove variables or functions",ex:"unset MY_VAR\nunset -f my_function",tags:"variable"},
{cat:"shell",cmd:"read",desc:"Read a line from input",ex:"read -p 'Name: ' name\nread -s -p 'Password: ' pass\nread -a arr <<< 'a b c'",tags:"input"},
{cat:"shell",cmd:"test",desc:"Evaluate conditions ([ ])",ex:"test -f file.txt && echo exists\n[ -d /var ] && echo dir\n[ \"$a\" = \"$b\" ]",tags:"condition"},
{cat:"shell",cmd:"expr",desc:"Evaluate expressions",ex:"expr 5 + 3\nexpr length 'hello'\nexpr substr 'hello' 1 3",tags:"math,evaluate"},
{cat:"shell",cmd:"bc",desc:"Arbitrary precision calculator",ex:"echo '5+3' | bc\necho 'scale=2; 10/3' | bc\necho '2^10' | bc",tags:"calculator"},
{cat:"shell",cmd:"cron",desc:"Schedule periodic tasks",ex:"crontab -e  # edit\ncrontab -l  # list\n# m h dom mon dow command\n0 2 * * * /backup.sh",tags:"schedule"},
{cat:"shell",cmd:"at",desc:"Schedule one-time tasks",ex:"echo 'backup.sh' | at 2am\necho 'reboot' | at now + 1 hour",tags:"schedule,once"},

// ===== Firewall & Security =====
{cat:"security",cmd:"iptables",desc:"Configure IPv4 packet filtering",ex:"sudo iptables -L\nsudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT\nsudo iptables -F",tags:"firewall"},
{cat:"security",cmd:"ufw",desc:"Uncomplicated Firewall (Ubuntu)",ex:"sudo ufw allow 80/tcp\nsudo ufw enable\nsudo ufw status verbose",tags:"firewall,ubuntu"},
{cat:"security",cmd:"firewalld",desc:"Dynamic firewall manager",ex:"sudo firewall-cmd --list-all\nsudo firewall-cmd --add-port=80/tcp --permanent\nsudo firewall-cmd --reload",tags:"firewall"},
{cat:"security",cmd:"openssl",desc:"OpenSSL cryptography toolkit",ex:"openssl genrsa -out key.pem 2048\nopenssl req -new -x509 -key key.pem -out cert.pem\nopenssl s_client -connect host:443",tags:"ssl,crypto"},
{cat:"security",cmd:"gpg",desc:"GNU Privacy Guard encryption",ex:"gpg --encrypt file.txt\ngpg --decrypt file.gpg\ngpg --gen-key",tags:"encrypt,pgp"},
{cat:"security",cmd:"ssh-keygen",desc:"Generate SSH key pairs",ex:"ssh-keygen -t ed25519 -C 'email'\nssh-keygen -t rsa -b 4096\nssh-keygen -f ~/.ssh/id_rsa",tags:"ssh,key"},
{cat:"security",cmd:"fail2ban",desc:"Ban IPs with too many failures",ex:"sudo fail2ban-client status\nsudo fail2ban-client status sshd\nsudo fail2ban-client set sshd unbanip IP",tags:"ban,security"},
{cat:"security",cmd:"chmod",desc:"Already in Permissions",ex:"see chmod above",tags:"permission"},

// ===== Performance & Monitoring =====
{cat:"monitor",cmd:"vmstat",desc:"Virtual memory statistics",ex:"vmstat\nvmstat 2 5  # every 2s, 5 times\nvmstat -s",tags:"memory,stats"},
{cat:"monitor",cmd:"mpstat",desc:"Processor statistics",ex:"mpstat\nmpstat -P ALL 2\nmpstat 1 5",tags:"cpu,stats"},
{cat:"monitor",cmd:"sar",desc:"System activity reporter",ex:"sar -u 1 5  # CPU\nsar -r  # memory\nsar -n DEV  # network",tags:"performance"},
{cat:"monitor",cmd:"iotop",desc:"I/O monitoring (top for disk)",ex:"sudo iotop\nsudo iotop -o  # only active",tags:"io,disk"},
{cat:"monitor",cmd:"iftop",desc:"Network bandwidth monitor",ex:"sudo iftop\nsudo iftop -i eth0\nsudo iftop -n",tags:"network,bandwidth"},
{cat:"monitor",cmd:"nethogs",desc:"Per-process network usage",ex:"sudo nethogs\nsudo nethogs eth0",tags:"network,per-process"},
{cat:"monitor",cmd:"glances",desc:"System monitoring (all-in-one)",ex:"glances\nglances -w  # web mode\nglances -t 2",tags:"monitor,all"},
{cat:"monitor",cmd:"strace",desc:"Trace system calls",ex:"strace ls /tmp\nstrace -p 1234\nstrace -c command  # summary",tags:"trace,debug"},
{cat:"monitor",cmd:"ltrace",desc:"Trace library calls",ex:"ltrace ./program\nltrace -p 1234",tags:"trace,library"},
{cat:"monitor",cmd:"perf",desc:"Linux profiling tools",ex:"sudo perf top\nsudo perf record command\nsudo perf report",tags:"profile"},
{cat:"monitor",cmd:"nload",desc:"Network traffic visualizer",ex:"nload\nnload eth0",tags:"network,visual"},

// ===== Misc / Utilities =====
{cat:"misc",cmd:"man",desc:"Display manual pages",ex:"man ls\nman 5 crontab\nman -k keyword  # search",tags:"help,manual"},
{cat:"misc",cmd:"tldr",desc:"Simplified man pages with examples",ex:"tldr tar\ntldr grep\ntldr find",tags:"help,simple"},
{cat:"misc",cmd:"which",desc:"Locate a command",ex:"which python3\nwhich nginx",tags:"locate,path"},
{cat:"misc",cmd:"whereis",desc:"Locate binary, source, man page",ex:"whereis python\nwhereis nginx",tags:"locate"},
{cat:"misc",cmd:"type",desc:"Display command type",ex:"type ls\ntype cd\ntype ll",tags:"info"},
{cat:"misc",cmd:"clear",desc:"Clear terminal screen",ex:"clear\nCtrl+L",tags:"terminal"},
{cat:"misc",cmd:"reset",desc:"Reset terminal to default",ex:"reset",tags:"terminal"},
{cat:"misc",cmd:"history",desc:"Already in System Info",ex:"see history above",tags:"history"},
{cat:"misc",cmd:"cowsay",desc:"ASCII cow speaks text",ex:"cowsay 'Hello!'\ncowthink 'Hmm...'\ncowsay -f tux 'Linux!'",tags:"fun"},
{cat:"misc",cmd:"figlet",desc:"ASCII art text banners",ex:"figlet Hello\necho 'Hi' | figlet",tags:"ascii,fun"},
{cat:"misc",cmd:"fortune",desc:"Random quotes/fortune",ex:"fortune\nfortune -o  # offensive\nfortune | cowsay",tags:"fun"},
{cat:"misc",cmd:"yes",desc:"Output a string repeatedly",ex:"yes | apt-get install package\nyes 'y' | command",tags:"auto-confirm"},
{cat:"misc",cmd:"seq",desc:"Print a sequence of numbers",ex:"seq 1 10\nseq 1 2 20\nseq -w 01 10",tags:"sequence,numbers"},
{cat:"misc",cmd:"shuf",desc:"Generate random permutations",ex:"shuf file.txt\nshuf -i 1-100 -n 5\necho 'a b c' | tr ' ' '\\n' | shuf",tags:"random,shuffle"},
{cat:"misc",cmd:"factor",desc:"Prime factorization",ex:"factor 42\nfactor 100",tags:"math,prime"},
{cat:"misc",cmd:"base64",desc:"Base64 encode/decode",ex:"echo 'hello' | base64\necho 'aGVsbG8K' | base64 -d",tags:"encode"},
{cat:"misc",cmd:"md5sum",desc:"Compute MD5 checksums",ex:"md5sum file.txt\nmd5sum *.iso > checksums.md5",tags:"hash,checksum"},
{cat:"misc",cmd:"sha256sum",desc:"Compute SHA256 checksums",ex:"sha256sum file.txt\nsha256sum -c checksums.sha256",tags:"hash,checksum"},
{cat:"misc",cmd:"mktemp",desc:"Create temporary file or directory",ex:"tmpfile=$(mktemp)\ntmpdir=$(mktemp -d)",tags:"temp"},
{cat:"misc",cmd:"sleep",desc:"Delay for a specified time",ex:"sleep 5\nsleep 2m\nsleep 1h 30m",tags:"delay"},
{cat:"misc",cmd:"timeout",desc:"Run command with time limit",ex:"timeout 10 ping google.com\ntimeout 5s ./script.sh",tags:"limit,time"},
{cat:"misc",cmd:"crontab",desc:"Already in Shell section",ex:"see cron above",tags:"schedule"},
];

const CATEGORIES = [
  {id:"file",name:"📁 File & Directory",desc:"Navigation, manipulation"},
  {id:"text",name:"📝 Text & Content",desc:"View, search, process text"},
  {id:"perms",name:"🔐 Permissions & Ownership",desc:"Access control"},
  {id:"process",name:"⚙️ Process Management",desc:"Jobs, signals, monitoring"},
  {id:"net",name:"🌐 Networking",desc:"Connections, transfer, DNS"},
  {id:"pkg",name:"📦 Package Management",desc:"Install, update, remove"},
  {id:"archive",name:"🗜️ Compression & Archive",desc:"Zip, tar, gzip"},
  {id:"system",name:"🖥️ System Information",desc:"Hardware, kernel, logs"},
  {id:"disk",name:"💾 Disk & Storage",desc:"Partitions, mount, format"},
  {id:"user",name:"👤 User & Group",desc:"Account management"},
  {id:"editor",name:"✏️ Text Editors",desc:"vim, nano, emacs"},
  {id:"shell",name:"🐚 Shell & Scripting",desc:"Variables, scheduling"},
  {id:"security",name:"🛡️ Firewall & Security",desc:"iptables, SSL, keys"},
  {id:"monitor",name:"📊 Performance & Monitoring",desc:"CPU, memory, network"},
  {id:"misc",name:"🔧 Utilities",desc:"Helpful tools & fun"},
];
